name: Web Interface Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/web/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/web/**'
  workflow_dispatch:

jobs:
  test:
    name: Run Web Interface Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/backend/requirements.txt
        pip install -r src/web/requirements.txt
        pip install pytest-cov selenium webdriver-manager

    - name: Lint with flake8
      run: |
        flake8 src/web --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/web --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics

    - name: Check formatting with black
      run: black --check src/web

    - name: Run unit tests
      run: pytest src/web/tests/unit/ -v

    - name: Run integration tests
      run: pytest src/web/tests/integration/ -v

    - name: Run functional tests
      run: pytest src/web/tests/functional/ -v

    - name: Install Chrome for Selenium
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run end-to-end tests
      run: pytest src/web/tests/e2e/ -v --headless

    - name: Generate coverage report
      run: pytest src/web/tests/ --cov=src/web --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true